### ISSUE TITLE
Progress bar failed when memory exceeds 1024GB

### ISSUE THREAD

**Issue by xiazeyu** [UVA-Computer-Vision-Lab/rivanna_resource#1] opened 2024-11-03 03:28 UTC
![CleanShot 2024-11-02 at 23 27 41@2x](https://github.com/user-attachments/assets/d7f8a2f6-6179-415d-98b2-dc2793eaa4ff)

**Comment by yaojin17** [comment] 2024-11-15 20:56
The problem is fixed in the latest commit.

**Closed as completed by yaojin17** 2024-11-15 20:56 UTC
